organization_id: ''
solution_id: ''
workspace_id: ''
workspace_key: a7wkDMtorv1
api_url: https://dev.api.cosmotech.com/v2-4-dev
resource_group_name: phoenixdev
resources_location: westeurope
adx_database_name: ''
digital_twin_url: ''
csm_simulator_repository: csmenginesdev
simulator_repository: simulator_simulator
simulator_version: ASSET_v14.2.0_2023-05-30-10h25-06Z
send_scenario_metadata_to_event_hub: true
use_dedicated_event_hub_namespace: true
deployment_name: Assetmtortestwebappv8
webapp_domain: ''
webapp_location: eastus2
webapp_repository: https://github.com/MohcineTor/Test-Web-App
webapp_repository_branch: deploy/asset
webapp_registration_id: ''
webapp_principal_id: ''
webapp_organization_url: https://cosmotech.com
webapp_insights_instrumentation_key: ''
webapp_enable_insights: false
webapp_static_domain: ''
adt_connector_id: ''
storage_connector_id: ''
twin_connector_id: ''
adt_dataset_id: ''
storage_dataset_id: ''
twin_dataset_id: ''
twincache_graphid: MTOR-RefDataSample-GraphId
terraform_cloud_workspace_id: ''
powerbi_workspace_id: ""
powerbi_api_scope: https://analysis.windows.net/powerbi/api/.default
datasetId: ''