api_url: https://dev.api.cosmotech.com/v2
api_scope: http://dev.api.cosmotech.com/.default
csm_platform_app_id: f6fbd519-9a53-4c6b-aabb-4919bb2d11be
csm_object_platform_id: 87267e78-0cff-4bd7-a4c5-8a68727f8cb7
csm_platform_scope_id: 6332363e-bcba-4c4a-a605-c25f23117400
azure_subscription: a24b131f-bd0b-42e8-872a-bded9b91ab74
azure_tenant_id: e413b834-8be8-4822-a370-be619545cb49
babylon_client_id: 4e5ca1cf-36d4-44b3-bf90-619e84ffa5d3
babylon_principal_id: 40451c55-b3ff-4d90-885d-a6f0c8f64851
redirect_uri_port: ""
adx_cluster_name: phoenixdev
adx_cluster_object_id: fb3cc984-9652-4536-9045-2a143bbe1a8f
resource_group_name: phoenixdev
csm_acr_registry_name: csmenginesdev
acr_registry_name: csmenginesdev
resources_location: westeurope
storage_account_name: csmphoenixdev
powerbi_api_scope: https://analysis.windows.net/powerbi/api/.default
azure_powerbi_group_id: 3cab658d-25e0-4452-9d0b-dd22276c4adf
azure_team_id: 25d59980-4644-4ba0-af6f-2ce9fae86c96