key: ${key}
name: ${name}
description: "${tag} Solution for testing the performance of RTE reference datasets"
repository: ${cosmotech['acr']['simulator_repository']}
version: ${cosmotech['acr']['simulator_version']}
tags:
- ${tag}
parameterGroups: []
parameters: []
runTemplates:
-   applyParameters: true
    computeSize: highmemory
    csmSimulation: AzureWebApp/AzureWebApp_Simulation
    datasetValidatorSource: local
    description: Run template for testing the performance of RTE reference datasets
    executionTimeout: null
    fetchDatasets: true
    fetchScenarioParameters: false
    gitBranchName: null
    gitRepositoryUrl: null
    id: ${cosmotech['api']['run_templates']}
    name: ${name}
    noDataIngestionState: false
    parameterGroups: []
    parametersHandlerSource: cloud
    parametersJson: false
    postRun: true
    postRunSource: cloud
    preRun: true
    preRunSource: cloud
    run: true
    runSource: local
    runTemplateSourceDir: null
    scenarioDataDownloadTransform: false
    scenariodataTransformSource: local
    sendDatasetsToDataWarehouse: false
    sendInputParametersToDataWarehouse: false
    stackSteps: false
    tags:
    - Assets
    validateData: false
url: https://github.com/Cosmo-Tech/aio.git
