key: ${key}
name: ${name}
description: "Workspace for solution"
solution:
  solutionId: ${cosmotech['api']['solution_id']}
  runTemplateFilter: null
  defaultRunTemplateDataset: null
useDedicatedEventHubNamespace: ${cosmotech['api']['use_dedicated_event_hub_namespace']}
sendScenarioMetadataToEventHub: ${cosmotech['api']['send_scenario_metadata_to_event_hub']}
sendInputToDataWarehouse: true
dedicatedEventHubSasKeyName: null
dedicatedEventHubAuthenticationStrategy: null
sendScenarioRunToEventHub: true
security:
  default: none
  accessControlList:
  - id: ${security_id}
    role: ${security_role}
webApp:
  url: https://${cosmotech['webapp']['static_domain']}
  options:
    charts:
      workspaceId: ${cosmotech['powerbi']['workspace']['id']}
      logInWithUserCredentials: false
      scenarioViewIframeDisplayRatio: 3.511111111111111
      dashboardsViewIframeDisplayRatio: 1.8686131386861313
      dashboardsView:
      scenarioView:
    instanceView:
      dataSource: null 
      dataContent: null
    menu:
      documentationUrl: https://portal.cosmotech.com/resources/platform-resources/platform-help
      supportUrl: https://support.cosmotech.com
      organizationUrl: https://cosmotech.com
