dedicatedEventHubAuthenticationStrategy: TENANT_CLIENT_CREDENTIALS
dedicatedEventHubSasKeyName: null
description: Workspace for testing the performance RTE reference datasets
key: PerformanceWorkspace
name: WP01 Performance
security:
    accessControlList:
    -   id: jerome.blanc@cosmotech.com
        role: admin
    -   id: mazou.ouedraogo@cosmotech.com
        role: admin
    -   id: john.folly@cosmotech.com
        role: admin
    -   id: jean-charles.planchenault@cosmotech.com
        role: admin
    -   id: paul.duvivier@cosmotech.com
        role: admin
    -   id: olivier.blancke@cosmotech.com
        role: admin
    -   id: mohammed.bali@cosmotech.com
        role: editor
    -   id: witold.krasny@cosmotech.com
        role: editor
    -   id: matthieu.bach@cosmotech.com
        role: editor
    -   id: ghislain.bordron@cosmotech.com
        role: editor
    default: editor
sendInputToDataWarehouse: null
sendScenarioMetadataToEventHub: true
sendScenarioRunToEventHub: true
solution:
    defaultRunTemplateDataset: null
    runTemplateFilter: null
    solutionId: ${deploy['solution_id']}
tags: null
useDedicatedEventHubNamespace: true
version: null
webApp:
    iframes: null
    options:
        charts:
            dashboardsView: []
            dashboardsViewIframeDisplayRatio: 1.8686131386861313
            logInWithUserCredentials: true
            scenarioView: []
            scenarioViewIframeDisplayRatio: 3.511111111111111
            workspaceId: null
        instanceView:
            dataContent: null
            dataSource: null
        menu:
            documentationUrl: ''
            organizationUrl: https://cosmotech.com
            supportUrl: https://support.cosmotech.com
    url: ''
